### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by TeamMonumenta** [rayman520/Monumenta_Speedruns#1]
Pretty please push the current version of the code :)

**Comment by Combustible** [comment]
Still hoping you'll push updated code for this...

**Comment by Combustible** [comment]
Maybe if I leave enough comments you'll notice the emails

**Comment by Combustible** [comment]
That would sure be nice

**Comment by Combustible** [comment]
The version here doesn't even have the /leadgen commands

**Comment by Combustible** [comment]
Which are now used for a bunch of other things besides speedruns.

**Comment by Combustible** [comment]
Would really help us in our push to update to 1.13 if I don't have to recreate a bunch of this code

**Comment by rayman520** [comment]
done, sry i missed this ;3

hope the 1.13 update is doing good
glhf

**Comment by TeamMonumenta** [comment]
Wooo awesome. Thanks!
